# Generated by Django 4.2.30 on 2026-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusarea',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='url',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='villagebooth',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='villagegallery',
            name='url',
        ),
        migrations.AddField(
            model_name='focusarea',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/focus-areas/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, upload_to='events/media/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='events/thumbnails/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='events/logos/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, upload_to='events/speakers/'),
        ),
        migrations.AddField(
            model_name='villagebooth',
            name='logo',
            field=models.ImageField(blank=True, upload_to='events/booth-logos/'),
        ),
        migrations.AddField(
            model_name='villagegallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/gallery/'),
        ),
        migrations.AlterField(
            model_name='expovillage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='events/villages/'),
        ),
    ]
