# Generated by Django 4.2.30 on 2026-08-29 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_focusarea_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expoevent',
            name='hero_images',
        ),
        migrations.CreateModel(
            name='ExpoEventHeroImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events/heroes/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='events.expoevent')),
            ],
            options={
                'db_table': 'event_hero_images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
