# Generated by Django 4.2.30 on 2026-08-29 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_expoevent_hero_images_expoeventheroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expovillage',
            name='why_visit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='VillageHighlight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='events.expovillage')),
            ],
            options={
                'db_table': 'village_highlights',
                'ordering': ['order', 'id'],
            },
        ),
    ]
