# Generated by Django 4.2.30 on 2026-08-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_align_landing_nav_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='initiation_channel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_link_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='DonationConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=40)),
                ('duplicate', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='cms.donation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
