# Generated by Django 4.2.30 on 2026-07-17 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qr.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=qr.models.generate_qr_code, max_length=32, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('destination_type', models.CharField(choices=[('hub', 'Smart Hub'), ('profile', 'Employee Profile'), ('project', 'Project'), ('event', 'Event'), ('product', 'Product'), ('organization', 'Organization'), ('website', 'Website'), ('social', 'Social'), ('custom', 'Custom URL')], default='hub', max_length=32)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_url', models.URLField(blank=True)),
                ('theme', models.CharField(choices=[('brand', 'Street Labs Brand'), ('dark', 'Dark'), ('light', 'Light'), ('custom', 'Custom')], default='brand', max_length=20)),
                ('primary_color', models.CharField(default='#ff6a00', max_length=20)),
                ('secondary_color', models.CharField(default='#0a1f44', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='qr/logos/')),
                ('show_logo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, help_text='Optional access password', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('activates_at', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('website', 'Website'), ('profile', 'Profile'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('location', 'Location'), ('meeting', 'Book Meeting'), ('portfolio', 'Portfolio'), ('contact', 'Download Contact'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'X / Twitter'), ('github', 'GitHub'), ('phone', 'Phone'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='qr.qrcode')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('device', models.CharField(blank=True, max_length=80)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('os', models.CharField(blank=True, max_length=80)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_returning', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('link_clicked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='qr.qrcodelink')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr.qrcode')),
            ],
            options={
                'verbose_name_plural': 'QR code analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
