# Generated by Django 4.2.30 on 2026-07-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodelink',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
